
<h3>Terms and Conditions</h3>
<div class="span-13">

<h4 > ESSENTIAL INFORMATION PLEASE READ THE FOLLOWING TERMS AND CONDITIONS. YOUR ACCEPTANCE OF THESE TERMS IS AN ABSOLUTE CONDITION OF YOUR USE OF THIS WEBSITE AND ITS PRODUCTS. </h4>
<p>CrowdPrep maintains a website site, www.CrowdPrep.com ("Website"), on which registered users ("Members") can browse, purchase and view Profiles. Members can also elect to become content contributors ("Contributors"). Contributors may upload profiles for the purpose of having CrowdPrep act as Contributor's agent for marketing Profiles to other users. By registering with CrowdPrep, Member agrees to the following:</p>
<h6 > 1. Consent. </h6>
<p>You must be at least 18 years of age or have parental consent to register with CrowdPrep. CrowdPrep may require that you provide sufficient proof that you are at least 18 years of age or have parental consent.</p>
<h6 > 2. Member Warranties and Responsibilities. </h6>
<P>
1.	Registration. Member warrants that he or she has provided CrowdPrep with accurate, complete, and current registration information at the time of registration and agrees to correct and update that information to ensure its accuracy and completeness at all times.Falsification of registration information, or failure to comply with these Terms of Service may result in loss of account, commissions, services or privileges provided by CrowdPrep.</p><p>
2.	Account Responsibility. All members who register with CrowdPrep will receive a password and a master account ("Master Account"). Each member is entirely responsible for any and all activities conducted through its Master Account and any Member names associated with that Master Account. Member may permit another individual to use the Master Account subject to Member's supervision and assumption of all resulting liabilities. Member agrees to notify CrowdPrep immediately of any unauthorized use of Member's password or accounts as well as of any other breach of security that may affect CrowdPrep. </p><p>
3.	One Account Per Member: Members are limited to one account, unless there is a pressing business or organizational reason for having more than one account and the consent of CrowdPrep is obtained. Members may not create additional accounts for the purpose of re-using promotional codes, affiliate program referrals or other bonus offers. A Member may not use more than one promotional code or offer without CrowdPrep's consent. Promotional codes and offers may not be combined. </p><p>
4.	Member Names. Upon registration as a Member of CrowdPrep, you may be asked to choose a Member name to identify yourself to other Members and CrowdPrep staff. You may not select or use a Member name of another person or a name that violates any third party's trademark or other proprietary right, which is or may be illegal to use, which may cause confusion with respect to the person's identity or association with other entities, or which CrowdPrep deems in its discretion to be vulgar or otherwise offensive. CrowdPrep reserves the right to delete any vulgar or otherwise offensive Member name, or to require the deletion thereof. </p><p>
5.	Former Members. Members whose accounts have been terminated by CrowdPrep may not access CrowdPrep in any manner or for any reason without the express written permission of CrowdPrep. Active Members may not knowingly allow former Members who have been terminated to use the active Members accounts. </p><p>
6.	By uploading content such as image files, Member warrants that he or she is the owner of the copyright thereto. </p><p>
7.	By uploading content, Member warrants that the content does not depict subject matter in a manner that violates any laws or individual rights. </p><p>
8.	By uploading content, Member warrants that the uploading was not done with the intent to harass, threaten, embarrass or cause distress, unwanted attention, or discomfort upon another person or entity. </p><p>
9.	By uploading a model release or otherwise representing that subjects depicted in an image file have consented to publication for whatever purpose, Member warrants that the information is complete and accurate. </p><p>
<h6 id=bold> 3. Image Credit Expiration and Refund Policy</h6>
Profile credit purchases are non-refundable. In the event that a refund is made, there will be a $10 processing fee assessed due to costs charged to CrowdPrep.com by the banking and credit card institutions.
> Profile credits expire one year after date of purchase. </p><p>
<h6 id=bold> 4. Uploading Content and Rights for Contributors</h6>
By uploading content such as Profile files, Member agrees to give CrowdPrep and all users the irrevocable nonexclusive royalty free rights to use the content for any purpose including publication, display, modification, and creation of derivative works, or products. Member also grants CrowdPrep use for any and all promotional purposes. CrowdPrep has the right to license any content up until the time Member removes the content from the Website. Once submitted to the Profile Approval Queue, Member may not remove Profiles from site until after they have been posted for 7 days, regardless of whether the Member chooses to terminate their account. Once content is uploaded to the Profile Approval Queue, Member must allow CrowdPrep the opportunity to license uses for at least 7 days. </p><p>

<h6 id=bold> 5. Compensation. </h6></p><p>
1.	CrowdPrep will pay Member the designated fee for Contributors described on the Website or by separate schedule for each valid download of an Profile file by a user. In the event that the fee described on the Website is different from that set forth in a schedule, the most current fee rate shall apply. </p><p>
2.	Contributors may request a payout when their account reaches $30 via PayPal or Moneybookers. Closing your account before it reaches $30 or breaking any terms or rules of this Member agreement can result in forfeiting your earnings. Commissions are payable after a short grace period noted on the website to verify that downloads are valid. Contributors who wish to receive a check must have at least $30 in earnings. </p><p>
3.	If you are a "US Person" as said term is defined by the IRS, a signed and completed IRS form W9 must be submitted to CrowdPrep for CrowdPrep to make payments to you. The Tax Center area inside your CrowdPrep account has instructions on how to submit this IRS form to us. A W9 is used to certify under penalties of perjury that your social security number is correct and that you are not subject to backup withholding taxes. Foreign persons might be subject to U.S. income tax on income they receive from U.S. sources. If you are a "Foreign Person" as said term is defined by the IRS, a signed and completed IRS form W8 must be submitted to CrowdPrep in order for you to claim a reduced rate of, or exemption from, withholding as a resident of a foreign country with which the United States has an income tax treaty. Instructions on how to submit this IRS form to us are inside the Tax Center in your CrowdPrep account area. </p><p>
<h6 id=bold> 6. Copyright. </h6>
Members retain all copyright that they own to uploaded Profiles. Member may not upload content to which they do not own the copyrights. </p><p>


<h6 id=bold> 7. Affiliate Program</h6>
The CrowdPrep Affiliate Program is intended to allow current Contributors to refer new Contributors to CrowdPrep. The CrowdPrep Affiliate Program is not to be used as a method for discounting your own purchases. Misrepresentations or fraudulent uses of the CrowdPrep Affiliate Program other than described herein may result in loss of services, commissions or other account privileges. </p><p>

<h6 id=bold> 8. Indemnification</h6>
Member shall indemnify, defend and hold harmless CrowdPrep, its officers, directors, employees, partners, associates, affiliates, joint venturers, agents and representatives, from any and all claims based on allegations which, if true, would constitute a breach of any of the foregoing warranties. The indemnity shall apply to any and all liabilities, losses, damages, expenses (including attorneys' fees and costs) and damages incurred by CrowdPrep as a result of such breach or breaches. CrowdPrep reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to the foregoing indemnification, without affecting Member's indemnity obligations. </p><p>

<h6 id=bold> 9. Control of Operations</h6>
1.	CrowdPrep, in its sole discretion, may remove any content uploaded to the Website including that appearing to infringe the intellectual property rights of other entities. </p><p>
2.	CrowdPrep reserves the right, but does not assume the responsibility, to restrict conduct which CrowdPrep deems in its discretion to be harmful to individual members, damaging to the communities that use CrowdPrep, or in violation of CrowdPrep's or any third party's rights. </p><p>
<h6 id=bold> 10. Disclaimers</h6>
1.	CrowdPrep expressly disclaims all warranties and conditions of any kind, either express or implied, including without limitation any implied warranties or conditions of merchantability, fitness for a particular purpose, non-infringement of third party rights, and those arising from a course of dealing or usage of trade. </p><p>
2.	CrowdPrep makes no warranty with respect to any legal advice or information regarding proper legal use of any Profile. Nothing on this website is intended as legal advice and CrowdPrep makes no claims or warranties as to the validity or correctness of any information that Member may assume is correct legal information or advice. Members are responsible for consulting their own attorneys to determine fitness of Profiles for particular purposes. Member agrees to hold harmess CrowdPrep from any claims related to Member's usage of Profiles. </p><p>
3.	CrowdPrep, its licensors, and subcontractors do not warrant any connection to, compatibility with, transmission over, nor results or use of, any network connection or facilities provided (or failed to be provided) through CrowdPrep. CrowdPrep may remove any content from the Website without any liability to Member. Members are responsible for assessing their computer and transmission network needs, and the results to be obtained therefrom. </p><p>
4.	CrowdPrep assumes no responsibility for any actions or liabilities arising from the possession or use of Profiles, files, or software obtained from CrowdPrep. </p><p>
5.	CrowdPrep makes no warranty that service will be uninterrupted, timely, secure, or error free. CrowdPrep makes no warranty as to the use or the results that may be obtained from the use of CrowdPrep. </p><p>
6.	CrowdPrep makes no warranty with respect to any related software or hardware used or provided by CrowdPrep. Any patent, copyright, trademark, trade secret or warranty issues, whether actual or alleged, are the direct responsibility of the manufacturer of said hardware or software product. </p><p>
<h6 id=bold> 11. Limitation of Liability</h6>
Member acknowledges that CrowdPrep shall not have any liability for any action taken with respect to the use of content. To the fullest extent permitted by applicable law, including but not limited to, negligence, CrowdPrep shall not be liable to Member for any indirect, incidental, special or consequential damages, including, without limitation, damages or loss of business, lost profits, business interruption, loss of business information, or any other pecuniary loss, even if CrowdPrep has been advised of the possibility of such damages. Member specifically agrees that CrowdPrep is not responsible or liable to Member or anyone else for any threatening, defamatory, obscene, offensive or illegal conduct or speech of any other party or any infringement or violation of another's rights, including intellectual property rights, rights of publicity, or rights of privacy. </p><p>

<h6 id=bold> 12. Termination</h6>
Either you or CrowdPrep may terminate your account with CrowdPrep at any time with or without cause. Your only right with respect to any dissatisfaction with any (i) Agreement term or policy or practice of CrowdPrep in operating CrowdPrep, (ii) content available through CrowdPrep or change therein, or (iii) amount or type of fees or billing methods, or change therein, is to terminate your account with CrowdPrep by notifying CrowdPrep Member Support of your desire to terminate by e-mail. As noted above in Section 4 "Uploading Content and Rights", any photos that have been approved may not be removed from the Website prior to the expiration of 7 days regardless of when Member chooses to terminate its account. In the event that your account is terminated due to impermissible conduct or fraud, Member agrees that access to CrowdPrep services, accounts, and commissions shall be forfeited. </p><p>

Accounts that are not accessed (logged into) for more than 2 years may be deemed terminated at the discretion of CrowdPrep. </p><p>

<h6 id=bold> 13. Impermissible Conduct</h6>
Member may not upload content which is unlawful and agrees to use CrowdPrep only for lawful purposes. Member may not post to or use CrowdPrep to transmit sexually explicit Profiles or other content which is deemed by CrowdPrep to be inappropriate Any conduct by Member that in CrowdPrep's sole discretion restricts or inhibits any other Member, person or entity from using or enjoying CrowdPrep or another service will not be permitted and shall give CrowdPrep the right to terminate the membership without notice. In the event that your account is terminated due to impermissible conduct or fraud, Member agrees that access to CrowdPrep services, accounts, and commissions earned may be forfeited. </p><p>

<h6 id=bold> 14. Severability</h6>
If any term or provision of this agreement is found to be unenforceable for any reason, this agreement shall remain in full force and effect and shall be fully enforceable on its remaining terms and conditions. </p><p>

<h6 id=bold> 15. Disputes, Attorney Fees, and Jurisdiction</h6>
This contract is governed by and shall be construed in accordance with the laws of the State of New York. The United Nations Convention on Contracts for the International Sale of Goods does not apply to or otherwise affect these TOS. You hereby consent to the personal jurisdiction of the state and federal courts located within such state. All actions, controversies and disputes arising from or relating to this agreement shall be heard and decided exclusively before the courts located within the State, County and City of New York and not elsewhere. You agree that service of process in any actions, controversies and disputes arising from or relating to these TOS may be effected by mailing a copy thereof by registered or certified mail (or any substantially similar form of mail), postage prepaid, to the other party however, nothing herein shall affect the right to effect service of process in any other manner permitted by law. This agreement shall be construed neither against nor in favor of any party, but rather in accordance with the fair meaning of the language hereof. The invalidity or unenforceability of any part of this agreement shall not affect the validity or enforceability of the balance hereof. </p><p>

<h6 id=bold> 16. Entire Agreement</h6>
You acknowledge that you have read this agreement, understand it, and agree to be bound by its terms and conditions. You further agree that it is the complete and exclusive statement of the understanding between you and CrowdPrep. Excluding any CrowdPrep Special Licensing agreement(s), this agreement supersedes any proposal or prior agreement, oral or written, and any other communication between you and CrowdPrep relating to the subject matter of this agreement. </p><p>

<h6 id=bold> 17. Revision of Agreement</h6>
CrowdPrep may revise this Agreement at any time and such revision shall be effective immediately upon the posting of the revised Agreement on the Website. You agree to review the Agreement prior to the uploading of an Profile to make yourself aware of such revisions. If any such revision is unacceptable to you, you may terminate your membership by notifying CrowdPrep Member Support of your desire to terminate by e-mail. Your notice of termination will be effective upon return receipt or notification by CrowdPrep. </p><p>
Questions? Please contact Customer Service here:

CrowdPrep<br></br>
New York, NY 10069<br></br>
USA <br></br>



</div>